### ISSUE TITLE
Ajouter la commande obtenir forme

### ISSUE THREAD

**Issue by grindcore819** [Lapsusone/Client-Formes#1]
Votre client doit se connecter au serveur, en recevoir 10 formes, les stocker dans une liste chaînée et se déconnecter du serveur.

L'usager doit pouvoir faire la commande "Obtenir formes" autant de fois qu'il veut. Les nouvelles formes remplaceront la liste
des anciennes formes. Il y aura au plus 10 formes dans la liste à la fois.

**Comment by Lapsusone** [comment]
Check branch issue1.
