### ISSUE TITLE
Un menu "Ordre" avec les options suivantes, dont une seule est active à la fois

### ISSUE THREAD

**Issue by grindcore819** [Lapsusone/Client-Formes#2]
utilisation obligatoire de JRadioButtonMenuItem !

- par numéro de séquence croissant
- par numéro de séquence décroissant
- par aire de forme croissante
- par aire de forme décroissante
- par type de forme dans l'ordre suivant :
- carré, rectangle, cercle, ovale, ligne
- par type de forme dans l'ordre inverse :
- ligne, ovale, cercle, rectangle, carré
- par distance (croissante) maximale entre deux points de la forme, par exemple pour un triangle et un - losange la distance

**Comment by Lapsusone** [comment]
Done. Reste implémentation. (merge issue 7)
