### ISSUE TITLE
Les Nodes sont fixes dans la liste chainée (#7)

### ISSUE THREAD

**Issue by Lapsusone** [Lapsusone/Client-Formes#9]
Quand on fait un tri, les nodes ne sont pas changés mais seulement les data. Dans ce cas previous et next perdent leur sens.

**Comment by grindcore819** [comment]
Ouais pour l'instant ^ca fait l'affaire je vais corriger ça demain

**Comment by Lapsusone** [comment]
J'ai fais quelques corrections repasse dessus voir si j'ai pas scrapper un ou deux tri 😝 (C'est testé)

**Comment by grindcore819** [comment]
c'est plus comme ca que je fais les tris

**Comment by grindcore819** [comment]
on peut se parler sur skype?
